# Generated by Django 2.2.3 on 2019-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('gtec', '0003_auto_20190724_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
