# Generated by Django 2.2.3 on 2020-03-16 21:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('gtec', '0004_auto_20191016_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('cpf', models.CharField(help_text='Digite apenas números', max_length=12, verbose_name='CPF')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Créditos')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para essa vaga', primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_dev', models.UUIDField(blank=True, null=True, verbose_name='Hora Devolução')),
                ('status', models.CharField(blank=True, choices=[('o', 'Ocupada'), ('d', 'Desocupada')], default='d', help_text='Disponibilidade da vaga', max_length=1)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vaga',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cpf', models.CharField(blank=True, help_text='Digite apenas numeros', max_length=12, verbose_name='CPF')),
                ('valor', models.CharField(max_length=30, null=True, verbose_name='Valor da vaga')),
                ('hora_operacao', models.DateTimeField(null=True, verbose_name='Hora da operação')),
                ('hora_prevista_saida', models.DateTimeField(null=True, verbose_name='Hora prevista para saída')),
                ('debito_id', models.UUIDField(default=uuid.uuid4)),
                ('id_vaga', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hora_saida', models.DateTimeField(null=True, verbose_name='Hora da saída')),
                ('nome_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtec.Clientes')),
            ],
            options={
                'verbose_name': 'Reserva de vagas',
                'verbose_name_plural': 'Reserva de vagas',
            },
        ),
    ]
