# Generated by Django 2.2.3 on 2020-03-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('gtec', '0006_auto_20200317_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Cliente'},
        ),
        migrations.AlterField(
            model_name='vaga',
            name='hora_dev',
            field=models.DateField(blank=True, null=True, verbose_name='Hora de Devolução'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='id',
            field=models.IntegerField(help_text='ID único para essa vaga', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
